name: Validation

on:
  workflow_call:
    inputs:
      do_fmt:
        description: "Run formatting step"
        required: false
        default: true
        type: boolean
      do_test:
        description: "Run test step"
        required: false
        default: true
        type: boolean
      do_build:
        description: "Run build step"
        required: false
        default: true
        type: boolean
      gomod_path:
        description: "Path to go.mod (default: repo root)"
        required: false
        default: "./"
        type: string

jobs:
  validate:
    environment: validation
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "${{ inputs.gomod_path }}go.mod"

      - name: Set PR number
        id: prmeta
        run: |
          echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT

      - name: Format code
        id: fmt
        if: ${{ inputs.DO_FMT }}
        run: |
          go fmt ./...
          if ! git diff --exit-code; then
            echo "Go code is not properly formatted"
            echo "unformatted_files<<EOF" >> $GITHUB_OUTPUT
            git diff --name-only >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            exit 1
          fi
        continue-on-error: true

      - name: Comment on PR if formatting fails
        if: steps.fmt.outcome == 'failure' && ${{ inputs.DO_FMT }}
        uses: actions/github-script@v7
        with:
          script: |
            const unformattedFiles = `${{ steps.fmt.outputs.unformatted_files }}`;
            const fileList = unformattedFiles.trim() ?
              unformattedFiles.split('\n').map(file => `- \`${file}\``).join('\n') :
              'No specific files detected';

            github.rest.issues.createComment({
              issue_number: ${{ steps.prmeta.outputs.pr_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `:x: **Go Format Failed**

              The following files need formatting:
              ${fileList}

              Please run \`go fmt ./...\` to format your code before merging.

              [See failed workflow run](${{
                github.server_url }}/${{
                github.repository
              }}/actions/runs/${{ github.run_id }})`
            })

      - name: Run tests
        id: test
        if: ${{ inputs.DO_TEST }}
        run: |
          if ! go test -v ./... 2>&1 | tee test_output.log; then
            echo "Tests failed"
            echo "test_failures<<EOF" >> $GITHUB_OUTPUT
            grep -A 10 -B 2 "FAIL\|panic\|Error" test_output.log | head -50 >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            exit 1
          fi
        continue-on-error: true

      - name: Comment on PR if tests fail
        if: steps.test.outcome == 'failure' && ${{ inputs.DO_TEST }}
        uses: actions/github-script@v7
        with:
          script: |
            const testFailures = `${{ steps.test.outputs.test_failures }}`;
            const failureDetails = testFailures.trim() ?
              `\`\`\`\n${testFailures}\n\`\`\`` :
              'No specific failure details captured';

            github.rest.issues.createComment({
              issue_number: ${{ steps.prmeta.outputs.pr_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `:x: **Go Tests Failed**

              Test failure details:
              ${failureDetails}

              Please fix test failures before merging.

              [See failed workflow run](${{
                github.server_url }}/${{
                github.repository
              }}/actions/runs/${{ github.run_id }})`
            })

      - name: Build project
        id: build
        if: ${{ inputs.DO_BUILD }}
        run: |
          go build ./...
        continue-on-error: true

      - name: Comment on PR if build fails
        if: steps.build.outcome == 'failure' && ${{ inputs.DO_BUILD }}
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ steps.prmeta.outputs.pr_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `:x: **Go Build Failed**
              Please fix build errors before merging.
              [See failed workflow run](${{
                github.server_url }}/${{
                github.repository
              }}/actions/runs/${{ github.run_id }})`
            })
